### ISSUE TITLE
Please can you do aarch64 wheels too 

### ISSUE THREAD

**Issue by sbishop61** [hoefling/so-59927844#1]
These are great on my Pi3+ but I have failed to get a working build for my Pi4 (Ubuntu 64) using your instructions on [SO ](https://stackoverflow.com/questions/59927844/is-it-possible-to-install-spacy-to-raspberry-pi-4-raspbian-buster/59957172?newreg=de30edfe046f4600927ad3a7ae451fa5) 

It would be really helpful if you could build the aarch64 wheels too.
Thanks
Stephen

**Comment by hoefling** [comment]
@sbishop61 unfortunately, I don't own a RPi 4 to generate the CPU-specifc config of supported features, so can't help here.

**Comment by sbishop61** [comment]
@hoefling thank you for the quick answer.

I tried your instructions on SO. Both cortexa57 and cortexa53. The build completes and it installs, but when I run tests it fails:
```
ubuntu@64U18D32Gb:~$ python3 -m blis.benchmark
Setting up data for gemm. 1000 iters,  nO=384 nI=384 batch_size=2000
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/blis/benchmark.py", line 107, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/blis/benchmark.py", line 76, in main
    numpy_blas = get_numpy_blas()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/blis/benchmark.py", line 19, in get_numpy_blas
    blas_libs = numpy.__config__.blas_opt_info["libraries"]
KeyError: 'libraries'
```

Or 
```
$ python3 -m blis.benchmark
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/ubuntu/SAB_Builds/SAB_spacy-build/cython-blis/blis/__init__.py", line 3, in <module>
    from .cy import init
ModuleNotFoundError: No module named 'blis.cy'
```

Any thoughts?
Thanks

**Comment by hoefling** [comment]
Looks like the cythonized extension was not compiled; you may have more luck asking the `blis` authors by [opening a new issue](https://github.com/explosion/cython-blis/issues/new).

**Comment by hoefling** [comment]
Ok, I've got my hands on an RPi4 now. Two issues here:

 1. RPi4 has a Cortex-A72 CPU and `blis` doesn't support it yet. Thus only `generic` arch possible.
 2. The `ModuleNotFoundError: No module named 'blis.cy'` is an issue on the current `blis` master, so don't use that, checkout to the `v0.4.2` tag which builds just fine.

You can find the wheels [here](https://github.com/hoefling/so-59927844/releases/tag/0.2). Note that the arch is still `armv7l` since Raspbian Buster didn't switch to 64bit yet.

**Comment by sbishop61** [comment]
Thanks for that
I am running Ubuntu 64 bit not Raspian. Can it be built for arvmv8

**Comment by hoefling** [comment]
I've uploaded the wheels for `aarch64`: [release 0.2](https://github.com/hoefling/so-59927844/releases/tag/0.2).

**Comment by sbishop61** [comment]
Thank you for your help.
They didn't install on my Pi 4 Ubuntu 20.04 Pip output:
`blis-0.4.1-cp37-cp37m-manylinux2014_aarch64.whl` is not a supported wheel on this platform`.

**Comment by hoefling** [comment]
That's probably because you are using another version of Python. Switch to 3.7.

**Comment by sbishop61** [comment]
Tried 3.7.7 and pip 19.2.3 with the same result `is not a supported wheel on this platform`

**Comment by hoefling** [comment]
What does
```sh
$ python3 -c "from pip._internal.pep425tags import get_supported; print(get_supported()[0])"
```
return? For `pip>20` the command is
```sh
$ python3 -c "from pip._internal.utils.compatibility_tags import get_supported; print(get_supported()[0])"
```

**Comment by sbishop61** [comment]
$ python3 -c "from pip._internal.pep425tags import get_supported; print(get_supported()[0])"
returns:
`('cp37', 'cp37m', 'linux_aarch64')`

**Comment by hoefling** [comment]
This means that Ubuntu doesn't offer official support for any of the manylinux peps, so ideally, the package must be built from source. You can rename the wheel, replacing the `manylinux2014` part with just `linux` so you're able to install the wheel, but on any runtime errors, you're on your own
